steps:
  - name: python
    entrypoint: pip
    dir: 'app'
    args: ['install', 
           '-r',
           'requirements.txt',
           '--user']

  - name: 'gcr.io/cloud-builders/docker'
    dir: 'app'
    args: ['build', 
           '-t', 
           'us-east4-docker.pkg.dev/${PROJECT_ID}/acg-demo-registry/acgflask:${SHORT_SHA}',
           '.']

  - name: 'gcr.io/cloud-builders/docker'
    dir: 'app'
    args: ['push',
           'us-east4-docker.pkg.dev/${PROJECT_ID}/acg-demo-registry/acgflask:${SHORT_SHA}']
  

  - name: google/cloud-sdk
    args: ['gcloud', 'run', 'deploy', 'acg-cloud-run', 
           '--image=us-east4-docker.pkg.dev/${PROJECT_ID}/acg-demo-registry/acgflask:${SHORT_SHA}', 
           '--region',
           'us-east4',
           '--platform',
           'managed', 
           '--allow-unauthenticated',
           '--port', 
           '8000']