steps:
  - name: python
    entrypoint: pip
    args: ['install', 
           '-r',
           'requirements.txt',
           '--user']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', 
           '-t', 
           '${_LOCATION}-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REGISTRY_REPO}/acgflask:${SHORT_SHA}',
           '.']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push',
           '${_LOCATION}-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REGISTRY_REPO}/acgflask:${SHORT_SHA}']
  

  - name: google/cloud-sdk
    args: ['gcloud', 'run', 'deploy', 'helloworld-${SHORT_SHA}', 
           '--image=${_LOCATION}-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REGISTRY_REPO}/acgflask:${SHORT_SHA}', 
           '--region',
           '${_LOCATION}',
           '--platform',
           'managed', 
           '--allow-unauthenticated',
           '--port', 
           '8000']