steps:
  - name: python
    entrypoint: pip
    dir: 'app'
    args: ['install', 
           '-r',
           'requirements.txt',
           '--user']

  - name: 'gcr.io/cloud-builders/docker'
    dir: 'app'
    args: ['build', 
           '-t', 
           '${_LOCATION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/acgflask:latest',
           '.']

  - name: 'gcr.io/cloud-builders/docker'
    dir: 'app'
    args: ['push',
           '${_LOCATION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/acgflask:latest']
  

  # - name: google/cloud-sdk
    # args: ['gcloud', 'run', 'deploy', 'helloworld-latest', 
    #        '--image=${_LOCATION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/acgflask:latest', 
    #        '--region',
    #        '${_LOCATION}',
    #        '--platform',
    #        'managed', 
    #        '--allow-unauthenticated',
    #        '--port', 
    #        '8000']